### ISSUE TITLE
Include steps to use the downloaded samples

### ISSUE THREAD

**Issue by nasht00** [driftyco/ionic-push-tutorial-app#8]
The tutorial says:

"or view the finished code here on Github!"

If I download the "finished" sample, what steps need to be taken to run it?

**Comment by Ionitron** [comment]
Greetings @nasht00!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
