### ISSUE TITLE
Does it support New Pushplugin 

### ISSUE THREAD

**Issue by bkrajendra** [driftyco/ionic-push-tutorial-app#9]
Does this ionic PUSH service supports new improved version of PhonegapPush plugin which is at
https://github.com/phonegap/phonegap-plugin-push.

The older plugin (https://github.com/phonegap-build/PushPlugin) is deprecated,and it is no longer maintained.

Please help!

**Comment by Ionitron** [comment]
Greetings @bkrajendra!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
